# Generated by Django 3.0.8 on 2020-07-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='confidence',
            field=models.DecimalField(decimal_places=4, default=0.4, max_digits=4),
        ),
        migrations.AddField(
            model_name='count',
            name='enterDirection',
            field=models.CharField(choices=[('U', 'Up'), ('D', 'Down'), ('L', 'Left'), ('R', 'Right')], default='Right', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='count',
            name='ip_path',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='count',
            name='model_path',
            field=models.CharField(default='mobilenet_ssd/MobileNetSSD_deploy.caffemodel', max_length=50),
        ),
        migrations.AddField(
            model_name='count',
            name='prototxt_path',
            field=models.CharField(default='mobilenet_ssd/MobileNetSSD_deploy.prototxt', max_length=50),
        ),
        migrations.AddField(
            model_name='count',
            name='skip_frames',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='count',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
