# Generated by Django 3.0.8 on 2020-07-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_auto_20200721_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='tracking',
            field=models.BooleanField(default=False),
        ),
    ]
